export const SHOP_SECTIONS = [
  {
    id: 1,
    title: 'HATS',
    subtitle: 'SHOP NOW',
    isWideDiv: false,
    linkUrl: '/hats',
    imageUrl: 'https://i.ibb.co/cvpntL1/hats.png',
  },
  {
    id: 2,
    title: 'JACKETS',
    subtitle: 'SHOP NOW',
    isWideDiv: false,
    linkUrl: '/jackets',
    imageUrl: 'https://i.ibb.co/px2tCc3/jackets.png',
  },
  {
    id: 3,
    title: 'SNEAKERS',
    subtitle: 'SHOP NOW',
    isWideDiv: false,
    linkUrl: '/sneakers',
    imageUrl: 'https://i.ibb.co/0jqHpnp/sneakers.png',
  },
  {
    id: 4,
    title: 'WOMENS',
    subtitle: 'SHOP NOW',
    isWideDiv: true,
    linkUrl: '/womens',
    imageUrl: 'https://i.ibb.co/GCCdy8t/womens.png',
  },
  {
    id: 5,
    title: 'MENS',
    subtitle: 'SHOP NOW',
    isWideDiv: true,
    linkUrl: '/mens',
    imageUrl: 'https://i.ibb.co/R70vBrQ/men.png',
  },
];
